### ISSUE TITLE
Problem with email validation

### ISSUE THREAD

**Issue by enriquepablo** [SUNET/edusign-app#114]
From Stefan:

I noticed that the email validation in the invite form does not work any more Enrique Perez. I think it stopped working when you fixed the bug that inactivated the send button when adding more people to the invite form.

**Comment by enrique** [comment]
Tagging wrong Enrique.

Regards

Enrique Martínez

________________________________
From: Enrique Pérez Arnaud ***@***.***>
Sent: Thursday, December 2, 2021 10:05:41 AM
To: SUNET/edusign-app ***@***.***>
Cc: MARTINEZ ZUÑIGA, ENRIQUE ***@***.***>; Mention ***@***.***>
Subject: [SUNET/edusign-app] Problem with email validation (Issue #114)


From Stefan:

I noticed that the email validation in the invite form does not work any more @enrique<https://github.com/enrique> Perez. I think it stopped working when you fixed the bug that inactivated the send button when adding more people to the invite form.
